### PR TITLE
Remove duplicates on open_manipulator_description launch files

### PR DESCRIPTION
**Pull request by Affonso-Gui**
Including `open_manipulator_model.launch` on `open_manipulator_rviz.launch` for easier understanding/ maintenance.

### CODE REVIEW

**Comment by Affonso-Gui** [comment]
Added commit to avoid duplicated code on urdf files by using `xacro:macro`.

**Comment by Affonso-Gui** [comment]
Maybe this PR too should be re-thought based on the new release and the `feature_robotis_manipulator` branch?

**Comment by gpwhd07** [comment]
Hi, @Affonso-Gui :>
Yes, we should consider this issue in the `feature_robotis_manipulator` branch.
I changed the branch but there is a conflict. I think because the moveit has been updated.
Please check about this.
Thank you.

**Comment by Affonso-Gui** [comment]
Probably conflicting with the updates. 
I'm closing this for now and if I find the same problem in the `feature_robotis_manipulator` branch I'll open a new PR.

**Pull request closed without merging**
