### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by Affonso-Gui**

### CODE REVIEW

**Comment by gpwhd07** [comment]
Hi @Affonso-Gui,
We have reason to use `getToolGoalValue` instead of `getToolValue`.
The `getToolGoalValue` function accesses `component_.at(name).tool.goal_value`, 
and the `getToolValue` function accesses `component_.at(name).tool.value`.

To shorten the control cycle, This controller doesn't read a present position of a gripper dynamixel(ID15) in every loop. Therefore, `tool.goal_value` is set when goal position of the gripper dynamixel(Id15) is write to the dynamixel, and this node publish the `tool.goal_value` as a previous goal value.

**Comment by Affonso-Gui** [comment]
Thanks for your answer.

Having a short test here I didn't saw any relevant changes to performance when using `ToolValue` rather than `ToolGoalValue`. Did you have any problems with it?

**Tests performed:**

Compared the publishing rate of `joint_states` with both `ToolValue` and `ToolGoalValue`.
- On normal settings, both publish at 100 hz.
- Adjusting iteration frequency and control time, both gave 1000 hz.
- In addition, performed the `ToolValue/ToolGoalValue` reading 10,000 times during the publishing loop, having 770 hz for `ToolValue` and 780 hz for `ToolGoalValue`

**Other comments:**

The following situations are not well supported by `GoalValue`:
- The gripper position at boot time is not read (always appears as 0.0)
- On current control or current based position control, the real position can significantly differ from the goal position

**Comment by Affonso-Gui** [comment]
On the `control_gui`, the bottom of the `y` on `y axis` was being cut and looking like a `v`, so tried changing it to uppercase.
lowercase
uppercase

**Comment by yhna** [comment]
Thank you for your review.

The `getToolGoalValue()` function returns the gripper's target position value, 
and the `getToolValue()` function returns the gripper's present position value received from dxl.

The present position of the gripper was not read every control cycle, at first.
However, we are now changing to reading the present position of the gripper every control cycle.

Therefore, data published to rosmsg should change all of the `getToolGoalValue()` functions to `getToolValue()`.

**Pull request merged**
